// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkiaoQ96SvxpIyklquHObkUJMLbCjrJUs',
    appId: '1:974166174300:web:a02de511e274b73f35d499',
    messagingSenderId: '974166174300',
    projectId: 'fluttertp-6ec9f',
    authDomain: 'fluttertp-6ec9f.firebaseapp.com',
    storageBucket: 'fluttertp-6ec9f.firebasestorage.app',
    measurementId: 'G-VSYYKZ77YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlNbQmHCDIf-42bgFsYs7B9_T0VgN7Ijg',
    appId: '1:974166174300:android:2b76362797b2561a35d499',
    messagingSenderId: '974166174300',
    projectId: 'fluttertp-6ec9f',
    storageBucket: 'fluttertp-6ec9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwObhfPQZkGGKHloSaABjKS_Mfhh5I8mA',
    appId: '1:974166174300:ios:10c227abb45dbf5f35d499',
    messagingSenderId: '974166174300',
    projectId: 'fluttertp-6ec9f',
    storageBucket: 'fluttertp-6ec9f.firebasestorage.app',
    iosBundleId: 'com.example.tp3App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwObhfPQZkGGKHloSaABjKS_Mfhh5I8mA',
    appId: '1:974166174300:ios:10c227abb45dbf5f35d499',
    messagingSenderId: '974166174300',
    projectId: 'fluttertp-6ec9f',
    storageBucket: 'fluttertp-6ec9f.firebasestorage.app',
    iosBundleId: 'com.example.tp3App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkiaoQ96SvxpIyklquHObkUJMLbCjrJUs',
    appId: '1:974166174300:web:814c8acec5776a6e35d499',
    messagingSenderId: '974166174300',
    projectId: 'fluttertp-6ec9f',
    authDomain: 'fluttertp-6ec9f.firebaseapp.com',
    storageBucket: 'fluttertp-6ec9f.firebasestorage.app',
    measurementId: 'G-7PXBS3EHCD',
  );
}
